### PR TITLE
Amymikhail labimportfunctions

### PR DESCRIPTION
**Pull request by AmyMikhail**
@jamesfuller-cdc and @sarahollis:

I have added all the functions necessary for the lab2godata shiny app, so these functions are now ready for review.

I have also done the following:

- The added functions are generalised - most except the wrapper function will also be useful for people working with other data apart from lab data or doing other manipulations, see documentation.
- DESCRIPTION is updated with additional required packages and author info
- README.md is updated (mainly formatting - I put it in a r markdown and knit to github)
- `devtools::documents()` (all fine)
- `devtools::check()` (one warning about tidyverse not being imported, but I don't know if that is one of my functions or not)
- `devtools::build()` (package built fine on my system

Note two things that I haven't done:

1. I was unable to find a way to translate characters from alphabets other than English - there's something that gets close to an approach that might work [here](https://github.com/isi-nlp/uroman) but it is written in perl and doesn't yet take diacritics (so won't really work for arabic scripts as all the vowel sounds would be missing).
2. I have not created a function to push lab data directly into Go.Data - as discussed, this is probably a step beyond what people want for matching anyway, and the `get_lab_fields()` function does provide the bones for any future developments along this path. 

Here are the functions that were added:

1. `lab2godata_wrapper()` - this is the master function that pulls in all the others to do the matching - you can use it to do everything that the shiny app will do but from a script.
2. `get_date_range()` - gets min and max date from a vector of dates
3. `mongify_date()` - converts character strings or date format into mongo db date/time format
4. `get_cases_epiwindow()` - retrieves cases from Go.Data within a date window (match to lab new lab results before importing)
5. `get_labresults_epiwindow()` - retrieve lab results from Go.Data within a date window (used for updating existing lab results)
6. `match_cases()` - matches lab results (or other data) with case or lab data from Go.Data, exports a match report and a clean file with the match IDs ready for importing into Go.Data.

In addition, there are four example data sets added to the package as .rd files in the data folder:

1. `new_lab_results` - example of a set of new lab results that need to be matched to cases for importing to Go.Data
2. `updated_lab_results` - example of sequencing results that need to be matched to existing lab records for importing to Go.Data and updating those records with the sequencing results.
3. `case_lookup_table` - example output from `get_cases_epiwindow()`, can be used to test different match protocols
4. `lab_lookup_table` - example output from `get_labresults_epiwindow()`, can be used  to test different match protocols

Finally, just to note that I have tested the functions mainly on r13, r21 and my own instance of Go.Data on my laptop.  R13 in particular I have set up so it can be used as a demo - all the lab reference data has been tidied up and the cases have all the necessary patient identifier columns to demonstrate the different match protocols.  I know Armand wanted this to be moved to a demo server, but I don't have access to that, so I recommend doing a full synch package (including ref data, outbreak templates and outbreak data etc) and importing that to the demo server.

I have only tested on small data sets, so this still needs testing for scalability on some larger data. 

I think even in its present state, Felipe could already beta test the lab2godata_wrapper function on some of his data if he wishes.

The only thing remaining is the shiny app that will just allow users to enter the arguments they want for the lab2godata_wrapper function.  Just let me know once you have reviewed the functions and accepted the pull request, as then I can include the proper install instructions for godataR.  If you have a .png of the logo that I could use for it that would be helpful as well.

### CODE REVIEW

**Comment by sarahollis** [comment]
@AmyMikhail @jamesfuller-cdc trying to figure out the easiest way to test this since remote package build is not working for me...
tinkering with adding it as a new release (pre-release in this case) which is linked to Amy's branch

James do you know how it works with the releases? can we install this package and specify the release?

**Comment by sarahollis** [comment]
I think we are fine to merge most of these things into main branch. Quick question @AmyMikhail  what is the rationale for creating the notes on .Rmd instead of just .md? reason being the logo looks very large and i'm not sure of a way to get the formatting right. if we could tinker with that so that it appears in right hand corner (smaller) then we can merge all.

**Comment by AmyMikhail** [comment]
Hi @sarahollis 

Creating the readme (or other how to / vignettes) in an .Rmd is better for the formatting of code etc (you can use R markdown, chunk settings etc.) and you just use `github_document` as the output in the YAML header and then knit after making any edits and it will create the .md.  The other advantage is that this fits with the package structure better as knit to github was intended for that purpose, so shouldn't create errors or warnings when you build the package and will alert you if there is anything in there that is inconsistent with other updates you have made to a function being demonstrated for example, when you run `devtools::check()`.  You can also use the same process to create the changelog and contributions tabs.

Agree that that logo is appearing enormous - I will check how to resize it and fix the alignment as well.

There are just a couple of other things I am fixing, specifically:

- I've added a `get_contacts_epiwindow()` function and am adding that to the `lab2godata_wrapper()` function, so that for new lab results both cases and contact lists will automatically be queried and the output will identify which is which.  I'll explain how this works when uploading the matched lab data in the vignette.
- I have created a more informative error message for when a user chooses columns to match on that are completely empty in the cases / contacts/ lab results data set that they are attempting to match with in Go.Data.  The error message will now tell you to explicitly choose a different set of columns to match on.  
- I am adding one other function that will create a basic case record from lab data when no matches are found - this will be entirely optional in the app and come with a health warning that I will explain in the vignette (i.e. only use this feature if you are absolutely sure that your lab results have come before any other case notification as otherwise it could create some duplicates, where for example the selected match method isn't optimal for that data set).

I'm aiming to get all this finished by the end of today, so would hold off on merging until I have pushed those changes (I'll update the merge request).

**Comment by sarahollis** [comment]
Hi @AmyMikhail open to others feedback but what do we think about separating the shiny app from the godataR package (i.e. house it in another repo?)
to me having the two blurred together will cause confusion going forward for maintenance etc.
if you want to be de-bugging the shiny app and adding new things, this should not affect the godataR package.
what are your thoughts? we could discuss today. just think that godataR could focus on smart ways to retrieve / post to API but something like a shinyapp could be in a standalone repo? cc @jamesfuller-cdc

**Comment by AmyMikhail** [comment]
Hi @sarahollis 

I was initially going to put it in a separate repo, but then I realised that it needs to be in an R package for `RInno` to work.  As all the functions it uses are now in `godataR` I figured it makes sense to put it in `godataR` as well, rather than put it in its own package and just make godataR a dependency.  To that end, I also made all the functions that feed into lab2godata a bit more generic, so they can be used independently of the app or even of lab data as well (for example you could potentially use `match_cases()` to match contacts with cases).  However we can discuss this afternoon - just to bear in mind though the way I have structured it up to now is quite tightly dependant on everything being in godataR so taking it out and creating a separate package at this stage would require some extra work - I'm sort of reluctant to do this as it has been quite handy having everything in the same package and being able to test different elements all together.

**Pull request merged**
